[platformio]
default_envs = ttgo_lora32_v21

[env:heltec_wifi_lora_32]
platform = espressif32
board = heltec_wifi_lora_32
framework = arduino
monitor_speed = 115200
build_flags =
  -D BOARD_HELTEC_WIFI_LORA_32
lib_deps =
  sandeepmistry/LoRa @ ^0.8.0

[env:lilygo_t3_v161]
platform = espressif32
board = ttgo-lora32-v1
framework = arduino
monitor_speed = 115200
build_flags =
  -D BOARD_LILYGO_T3_V161
lib_deps =
  sandeepmistry/LoRa @ ^0.8.0

[env:ttgo_lora32_v21]
platform = espressif32
board = ttgo-lora32-v21
framework = arduino
monitor_speed = 115200
build_flags =
  -D BOARD_TTGO_LORA32_V21
lib_deps =
  sandeepmistry/LoRa @ ^0.8.0
